### PR TITLE
Update pykwalify to 1.8.0

### PR DESCRIPTION
**Pull request by mencian**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mencian** [comment]
@conda-forge-admin, please rerender

**Comment by mencian** [comment]
Hello, @jakirkham, could you review the changes I've made when you get a chance? I have also added myself as a recipe maintainer if that is OK with you.

**Comment by traversaro** [comment]
@conda-forge/pykwalify @jakirkham friendly ping, this is currently block https://github.com/conda-forge/west-feedstock/pull/2, thanks!

**Comment by dopplershift** [comment]
I'm going to go ahead and merge this because the changes look good and the current package (1.7.0) is broken on Python 3.12 due to its use of `import imp`, which was removed in 3.12.

**Pull request merged**
