### PR TITLE
update to version 1.6

### PR DESCRIPTION
**Pull request by cokelaer**
This is also required to have pykwalify available for python3.6

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by cokelaer** [comment]
@isuruf everything seems to have passed correctly. I believe that you have to merge the pull request now. thanks

**Comment by cokelaer** [comment]
@isuruf @conda-forge-admin sorry to pester you with this, could anyone with write access merge the pull requests ? thanks in advance

**Comment by cokelaer** [comment]
@jakirkham @isuruf any feedback / update on this pull request ? thanks

**Comment by jakirkham** [comment]
Sorry, missed the pings.

This doesn't appear to be adding Python 3.6 to the matrices though. 😕 Would encourage you to investigate the dependencies and make sure they exist in Python 3.6 form (also note the very tight pinnings of the requirements).

There are probably some other things that this recipe could use like inclusion of a license file from the source in the package. Dropping requirements from `build` other than `python` and `setuptools`. Considering using `pip` to do the install. Verifying the dependency pinnings used are still accurate. Maybe there are other things like this that I have missed.

**Comment by cokelaer** [comment]
- I fixed the tight pinning of the dependencies (this was in the previous version 1.5 but indeed less strict in the newest version 1.6)
- I removed the deps in the build section
- locally, it compiles on py36, so let us have another go through travis and other checks to see whether this new version will be compiled for py36
- I'll keep the license as it is for now (source code says MIT as mentionned in this recipe)

**Comment by cokelaer** [comment]
right now python-dateutil requires >=2.4.2

version 2.4.2 is for py35 and py27 only

I will try to use python-dateutil >=2.6.1  (which is on py36) just to see if it trigs the py36 on circle and travis.

**Comment by cokelaer** [comment]
Wierd, indeed the python3.6 does not seem to be triggere. I don't know what to do or what is going on here. All dependencies are available for py36.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
As to `python-dateutil`, would leave the original version constraint. It doesn't block us from getting a newer version for Python 3.6.

**Comment by jakirkham** [comment]
Ah! The re-rendering bot needs permissions to push to your branch. Can you please check the allow edits box on your, @cokelaer?

**Comment by cokelaer** [comment]
I have updated the python-dateutil version.
As for the "allow edits box", this is wierd, I do not see the pull request in my fork anymore and I cannot see the "edit box".

**Comment by jakirkham** [comment]
There should be a checkbox in the PR on the right below the subscribe button. GitHub doc section linked below.

ref: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by cokelaer** [comment]
okay, so py36 was not in the .travis file, which I updated accordingly. The travis is not running for py27,py35 and py36.

**Comment by jakirkham** [comment]
So we should be able to fix the CI files once the allow edits checkbox is checked as the bot can push a fix to your PR. Unfortunately it can’t push until the box is checked.

**Comment by cokelaer** [comment]
if you are speaking about the button on this page, indeed I check it but got this error/warning message in the top of the page in a read box : " You can't perform that action at this time. "

**Comment by cokelaer** [comment]
although, saying that the box is checked now.

**Comment by jakirkham** [comment]
Strange. :/ Well let’s give it a try.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by cokelaer** [comment]
great. looks like it worked on travis and CI

**Comment by cokelaer** [comment]
@jakirkham I believe we can merge: the py27, py35, py36 have compiled. what do you think ?

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks @cokelaer for your patience and hard work here. Very much appreciated.

Also thanks @isuruf for making sure I didn't miss this one.

**Comment by cokelaer** [comment]
@jakirkham thanks to you.

**Comment by jakirkham** [comment]
If you are interested, would be happy to have you as a maintainer here @cokelaer. Just let us know if that is something you would be interested in.

**Pull request merged**
